package com.emiadda.wsdl.categoriesAndProducts;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 07/07/2016
//
//---------------------------------------------------



public interface VOKIServiceEvents
{
    public void Starting();
    public void Completed(VOKOperationResult result);
}
