package com.emiadda.wsdl.PaymentModel;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 02/08/2016
//
//---------------------------------------------------



public interface ELLIServiceEvents
{
    public void Starting();
    public void Completed(ELLOperationResult result);
}
