package com.emiadda.wsdl.getCategories;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 04/07/2016
//
//---------------------------------------------------



public interface ABMIServiceEvents
{
    public void Starting();
    public void Completed(ABMOperationResult result);
}
