package com.emiadda.wsdl.getCategories;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.1
//
// Created by Quasar Development at 02/08/2016
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.transport.HttpsTransportSE;

import java.util.List;


public class ELLserverBinding
{
    interface ELLIWcfMethod
    {
        ELLExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(ELLExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://www.mydevsystems.com/dev/emiaddanew/jnusoap/emiadda/getCategories.php";

    int timeOut=20000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    ELLIServiceEvents callback;
    public ELLserverBinding(){}

    public ELLserverBinding (ELLIServiceEvents callback)
    {
        this.callback = callback;
    }
    public ELLserverBinding(ELLIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public ELLserverBinding(ELLIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected ELLExtendedSoapSerializationEnvelope createEnvelope()
    {
        ELLExtendedSoapSerializationEnvelope envelope= new ELLExtendedSoapSerializationEnvelope(ELLExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,ELLExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,ELLExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public String getCategories(final String _params ) throws java.lang.Exception
    {
        return (String)execute(new ELLIWcfMethod()
        {
            @Override
            public ELLExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ELLExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:server", "getCategories");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="params";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_params!=null?_params:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ELLExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("result");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:server#getCategories");
    }
    
    public android.os.AsyncTask< Void, Void, ELLOperationResult< String>> getCategoriesAsync(final String _params)
    {
        return executeAsync(new ELLFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getCategories( _params);
            }
        });
    }
    
    public String getProductsByCategory(final String _params ) throws java.lang.Exception
    {
        return (String)execute(new ELLIWcfMethod()
        {
            @Override
            public ELLExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ELLExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:server", "getProductsByCategory");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="params";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_params!=null?_params:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ELLExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("result");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:server#getProductsByCategory");
    }
    
    public android.os.AsyncTask< Void, Void, ELLOperationResult< String>> getProductsByCategoryAsync(final String _params)
    {
        return executeAsync(new ELLFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getProductsByCategory( _params);
            }
        });
    }
    
    public String getProductByProductID(final String _params ) throws java.lang.Exception
    {
        return (String)execute(new ELLIWcfMethod()
        {
            @Override
            public ELLExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ELLExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:server", "getProductByProductID");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="params";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_params!=null?_params:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(ELLExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("result");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:server#getProductByProductID");
    }
    
    public android.os.AsyncTask< Void, Void, ELLOperationResult< String>> getProductByProductIDAsync(final String _params)
    {
        return executeAsync(new ELLFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getProductByProductID( _params);
            }
        });
    }
    
    public String getProductImage(final String _params ) throws java.lang.Exception
    {
        return (String)execute(new ELLIWcfMethod()
        {
            @Override
            public ELLExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ELLExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:server", "getProductImage");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="params";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(_params!=null?_params:SoapPrimitive.NullNilElement);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ELLExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("result");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:server#getProductImage");
    }
    
    public android.os.AsyncTask< Void, Void, ELLOperationResult< String>> getProductImageAsync(final String _params)
    {
        return executeAsync(new ELLFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getProductImage( _params);
            }
        });
    }
    
    public String getSpecials() throws java.lang.Exception
    {
        return (String)execute(new ELLIWcfMethod()
        {
            @Override
            public ELLExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ELLExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:server", "getSpecials");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="params";
                __info.type = PropertyInfo.BOOLEAN_CLASS;
                __info.setValue(true);
                __soapReq.addProperty(__info);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ELLExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("result");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:server#getSpecials");
    }
    
    public android.os.AsyncTask< Void, Void, ELLOperationResult< String>> getSpecialsAsync(final String _params)
    {
        return executeAsync(new ELLFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getSpecials();
            }
        });
    }
    
    public String placeOrder(final String orderParams,final String productsParam,final String totalParams) throws java.lang.Exception
    {
        return (String)execute(new ELLIWcfMethod()
        {
            @Override
            public ELLExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
                ELLExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("urn:server", "placeOrder");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="params";
                __info.type = PropertyInfo.STRING_CLASS;
                __info.setValue(orderParams);
                __soapReq.addProperty(__info);

                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="products_array";
                __info.type = PropertyInfo.VECTOR_CLASS;
                __info.setValue(productsParam);
                __soapReq.addProperty(__info);

                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="total_array";
                __info.type = PropertyInfo.VECTOR_CLASS;
                __info.setValue(totalParams);
                __soapReq.addProperty(__info);

                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(ELLExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                SoapObject __soap=(SoapObject)__result;
                java.lang.Object obj = __soap.getProperty("result");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return j.toString();
                }
                else if (obj!= null && obj instanceof String){
                    return (String)obj;
                }
                return null;
            }
        },"urn:server#placeOrder");
    }
    
    public android.os.AsyncTask< Void, Void, ELLOperationResult< String>> placeOrderAsync(final String _params,final String products_array,final String total_array)
    {
        return executeAsync(new ELLFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return placeOrder( _params,products_array,total_array);
            }
        });
    }

    
    protected java.lang.Object execute(ELLIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ELLExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, ELLOperationResult< T>>  executeAsync(final ELLFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, ELLOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected ELLOperationResult< T> doInBackground(Void... params) {
                ELLOperationResult< T> result = new ELLOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(ELLOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,ELLExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


