package com.emiadda.server;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 8/3/2016 5:50:27 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class orderparams implements KvmSerializable {
    
    public String store_id;
    public String store_name;
    public String invoice_prefix;
    public String store_url;
    public String customer_id;
    public String customer_group_id;
    public String firstname;
    public String lastname;
    public String email;
    public String telephone;
    public String fax;
    public String custom_field;
    public String payment_firstname;
    public String payment_lastname;
    public String payment_company;
    public String payment_address_1;
    public String payment_address_2;
    public String payment_city;
    public String payment_postcode;
    public String payment_country;
    public String payment_country_id;
    public String payment_zone;
    public String payment_zone_id;
    public String payment_district_id;
    public String payment_subzone_id;
    public String payment_address_format;
    public String payment_custom_field;
    public String payment_method;
    public String payment_code;
    public String shipping_firstname;
    public String shipping_lastname;
    public String shipping_company;
    public String shipping_address_1;
    public String shipping_address_2;
    public String shipping_city;
    public String shipping_postcode;
    public String shipping_country;
    public String shipping_country_id;
    public String shipping_zone;
    public String shipping_zone_id;
    public String shipping_district_id;
    public String shipping_subzone_id;
    public String shipping_address_format;
    public String shipping_custom_field;
    public String shipping_method;
    public String shipping_code;
    public String comment;
    public String total;
    public String affiliate_id;
    public String commission;
    public String marketing_id;
    public String tracking;
    public String language_id;
    public String currency_id;
    public String currency_code;
    public String currency_value;
    public String ip;
    public String forwarded_ip;
    public String user_agent;
    public String accept_language;
    public String emi;
    public String method;
    public String totalamt;
    public String shipping_charge;
    public String down_payment;
    public String each_emi;
    public String customer_type;
    public String no_of_emi;
    public String payable_mrp;
    public String vat;
    public String cod_type;
    public String selected_num_emi;
    public String per_emi;
    
    public orderparams(){}
    
    public orderparams(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("store_id"))
        {
            Object obj = soapObject.getProperty("store_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                store_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                store_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("store_name"))
        {
            Object obj = soapObject.getProperty("store_name");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                store_name = j.toString();
            }else if (obj!= null && obj instanceof String){
                store_name = (String) obj;
            }
        }
        if (soapObject.hasProperty("invoice_prefix"))
        {
            Object obj = soapObject.getProperty("invoice_prefix");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                invoice_prefix = j.toString();
            }else if (obj!= null && obj instanceof String){
                invoice_prefix = (String) obj;
            }
        }
        if (soapObject.hasProperty("store_url"))
        {
            Object obj = soapObject.getProperty("store_url");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                store_url = j.toString();
            }else if (obj!= null && obj instanceof String){
                store_url = (String) obj;
            }
        }
        if (soapObject.hasProperty("customer_id"))
        {
            Object obj = soapObject.getProperty("customer_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                customer_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                customer_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("customer_group_id"))
        {
            Object obj = soapObject.getProperty("customer_group_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                customer_group_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                customer_group_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("firstname"))
        {
            Object obj = soapObject.getProperty("firstname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                firstname = j.toString();
            }else if (obj!= null && obj instanceof String){
                firstname = (String) obj;
            }
        }
        if (soapObject.hasProperty("lastname"))
        {
            Object obj = soapObject.getProperty("lastname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                lastname = j.toString();
            }else if (obj!= null && obj instanceof String){
                lastname = (String) obj;
            }
        }
        if (soapObject.hasProperty("email"))
        {
            Object obj = soapObject.getProperty("email");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                email = j.toString();
            }else if (obj!= null && obj instanceof String){
                email = (String) obj;
            }
        }
        if (soapObject.hasProperty("telephone"))
        {
            Object obj = soapObject.getProperty("telephone");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                telephone = j.toString();
            }else if (obj!= null && obj instanceof String){
                telephone = (String) obj;
            }
        }
        if (soapObject.hasProperty("fax"))
        {
            Object obj = soapObject.getProperty("fax");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                fax = j.toString();
            }else if (obj!= null && obj instanceof String){
                fax = (String) obj;
            }
        }
        if (soapObject.hasProperty("custom_field"))
        {
            Object obj = soapObject.getProperty("custom_field");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                custom_field = j.toString();
            }else if (obj!= null && obj instanceof String){
                custom_field = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_firstname"))
        {
            Object obj = soapObject.getProperty("payment_firstname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_firstname = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_firstname = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_lastname"))
        {
            Object obj = soapObject.getProperty("payment_lastname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_lastname = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_lastname = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_company"))
        {
            Object obj = soapObject.getProperty("payment_company");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_company = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_company = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_address_1"))
        {
            Object obj = soapObject.getProperty("payment_address_1");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_address_1 = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_address_1 = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_address_2"))
        {
            Object obj = soapObject.getProperty("payment_address_2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_address_2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_address_2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_city"))
        {
            Object obj = soapObject.getProperty("payment_city");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_city = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_city = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_postcode"))
        {
            Object obj = soapObject.getProperty("payment_postcode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_postcode = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_postcode = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_country"))
        {
            Object obj = soapObject.getProperty("payment_country");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_country = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_country = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_country_id"))
        {
            Object obj = soapObject.getProperty("payment_country_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_country_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_country_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_zone"))
        {
            Object obj = soapObject.getProperty("payment_zone");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_zone = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_zone = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_zone_id"))
        {
            Object obj = soapObject.getProperty("payment_zone_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_zone_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_zone_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_district_id"))
        {
            Object obj = soapObject.getProperty("payment_district_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_district_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_district_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_subzone_id"))
        {
            Object obj = soapObject.getProperty("payment_subzone_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_subzone_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_subzone_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_address_format"))
        {
            Object obj = soapObject.getProperty("payment_address_format");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_address_format = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_address_format = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_custom_field"))
        {
            Object obj = soapObject.getProperty("payment_custom_field");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_custom_field = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_custom_field = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_method"))
        {
            Object obj = soapObject.getProperty("payment_method");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_method = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_method = (String) obj;
            }
        }
        if (soapObject.hasProperty("payment_code"))
        {
            Object obj = soapObject.getProperty("payment_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payment_code = j.toString();
            }else if (obj!= null && obj instanceof String){
                payment_code = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_firstname"))
        {
            Object obj = soapObject.getProperty("shipping_firstname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_firstname = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_firstname = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_lastname"))
        {
            Object obj = soapObject.getProperty("shipping_lastname");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_lastname = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_lastname = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_company"))
        {
            Object obj = soapObject.getProperty("shipping_company");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_company = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_company = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_address_1"))
        {
            Object obj = soapObject.getProperty("shipping_address_1");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_address_1 = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_address_1 = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_address_2"))
        {
            Object obj = soapObject.getProperty("shipping_address_2");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_address_2 = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_address_2 = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_city"))
        {
            Object obj = soapObject.getProperty("shipping_city");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_city = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_city = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_postcode"))
        {
            Object obj = soapObject.getProperty("shipping_postcode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_postcode = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_postcode = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_country"))
        {
            Object obj = soapObject.getProperty("shipping_country");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_country = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_country = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_country_id"))
        {
            Object obj = soapObject.getProperty("shipping_country_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_country_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_country_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_zone"))
        {
            Object obj = soapObject.getProperty("shipping_zone");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_zone = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_zone = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_zone_id"))
        {
            Object obj = soapObject.getProperty("shipping_zone_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_zone_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_zone_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_district_id"))
        {
            Object obj = soapObject.getProperty("shipping_district_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_district_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_district_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_subzone_id"))
        {
            Object obj = soapObject.getProperty("shipping_subzone_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_subzone_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_subzone_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_address_format"))
        {
            Object obj = soapObject.getProperty("shipping_address_format");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_address_format = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_address_format = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_custom_field"))
        {
            Object obj = soapObject.getProperty("shipping_custom_field");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_custom_field = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_custom_field = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_method"))
        {
            Object obj = soapObject.getProperty("shipping_method");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_method = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_method = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_code"))
        {
            Object obj = soapObject.getProperty("shipping_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_code = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_code = (String) obj;
            }
        }
        if (soapObject.hasProperty("comment"))
        {
            Object obj = soapObject.getProperty("comment");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                comment = j.toString();
            }else if (obj!= null && obj instanceof String){
                comment = (String) obj;
            }
        }
        if (soapObject.hasProperty("total"))
        {
            Object obj = soapObject.getProperty("total");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                total = j.toString();
            }else if (obj!= null && obj instanceof String){
                total = (String) obj;
            }
        }
        if (soapObject.hasProperty("affiliate_id"))
        {
            Object obj = soapObject.getProperty("affiliate_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                affiliate_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                affiliate_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("commission"))
        {
            Object obj = soapObject.getProperty("commission");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                commission = j.toString();
            }else if (obj!= null && obj instanceof String){
                commission = (String) obj;
            }
        }
        if (soapObject.hasProperty("marketing_id"))
        {
            Object obj = soapObject.getProperty("marketing_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                marketing_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                marketing_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("tracking"))
        {
            Object obj = soapObject.getProperty("tracking");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                tracking = j.toString();
            }else if (obj!= null && obj instanceof String){
                tracking = (String) obj;
            }
        }
        if (soapObject.hasProperty("language_id"))
        {
            Object obj = soapObject.getProperty("language_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                language_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                language_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("currency_id"))
        {
            Object obj = soapObject.getProperty("currency_id");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                currency_id = j.toString();
            }else if (obj!= null && obj instanceof String){
                currency_id = (String) obj;
            }
        }
        if (soapObject.hasProperty("currency_code"))
        {
            Object obj = soapObject.getProperty("currency_code");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                currency_code = j.toString();
            }else if (obj!= null && obj instanceof String){
                currency_code = (String) obj;
            }
        }
        if (soapObject.hasProperty("currency_value"))
        {
            Object obj = soapObject.getProperty("currency_value");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                currency_value = j.toString();
            }else if (obj!= null && obj instanceof String){
                currency_value = (String) obj;
            }
        }
        if (soapObject.hasProperty("ip"))
        {
            Object obj = soapObject.getProperty("ip");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                ip = j.toString();
            }else if (obj!= null && obj instanceof String){
                ip = (String) obj;
            }
        }
        if (soapObject.hasProperty("forwarded_ip"))
        {
            Object obj = soapObject.getProperty("forwarded_ip");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                forwarded_ip = j.toString();
            }else if (obj!= null && obj instanceof String){
                forwarded_ip = (String) obj;
            }
        }
        if (soapObject.hasProperty("user_agent"))
        {
            Object obj = soapObject.getProperty("user_agent");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                user_agent = j.toString();
            }else if (obj!= null && obj instanceof String){
                user_agent = (String) obj;
            }
        }
        if (soapObject.hasProperty("accept_language"))
        {
            Object obj = soapObject.getProperty("accept_language");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                accept_language = j.toString();
            }else if (obj!= null && obj instanceof String){
                accept_language = (String) obj;
            }
        }
        if (soapObject.hasProperty("emi"))
        {
            Object obj = soapObject.getProperty("emi");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                emi = j.toString();
            }else if (obj!= null && obj instanceof String){
                emi = (String) obj;
            }
        }
        if (soapObject.hasProperty("method"))
        {
            Object obj = soapObject.getProperty("method");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                method = j.toString();
            }else if (obj!= null && obj instanceof String){
                method = (String) obj;
            }
        }
        if (soapObject.hasProperty("totalamt"))
        {
            Object obj = soapObject.getProperty("totalamt");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                totalamt = j.toString();
            }else if (obj!= null && obj instanceof String){
                totalamt = (String) obj;
            }
        }
        if (soapObject.hasProperty("shipping_charge"))
        {
            Object obj = soapObject.getProperty("shipping_charge");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                shipping_charge = j.toString();
            }else if (obj!= null && obj instanceof String){
                shipping_charge = (String) obj;
            }
        }
        if (soapObject.hasProperty("down_payment"))
        {
            Object obj = soapObject.getProperty("down_payment");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                down_payment = j.toString();
            }else if (obj!= null && obj instanceof String){
                down_payment = (String) obj;
            }
        }
        if (soapObject.hasProperty("each_emi"))
        {
            Object obj = soapObject.getProperty("each_emi");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                each_emi = j.toString();
            }else if (obj!= null && obj instanceof String){
                each_emi = (String) obj;
            }
        }
        if (soapObject.hasProperty("customer_type"))
        {
            Object obj = soapObject.getProperty("customer_type");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                customer_type = j.toString();
            }else if (obj!= null && obj instanceof String){
                customer_type = (String) obj;
            }
        }
        if (soapObject.hasProperty("no_of_emi"))
        {
            Object obj = soapObject.getProperty("no_of_emi");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                no_of_emi = j.toString();
            }else if (obj!= null && obj instanceof String){
                no_of_emi = (String) obj;
            }
        }
        if (soapObject.hasProperty("payable_mrp"))
        {
            Object obj = soapObject.getProperty("payable_mrp");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                payable_mrp = j.toString();
            }else if (obj!= null && obj instanceof String){
                payable_mrp = (String) obj;
            }
        }
        if (soapObject.hasProperty("vat"))
        {
            Object obj = soapObject.getProperty("vat");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                vat = j.toString();
            }else if (obj!= null && obj instanceof String){
                vat = (String) obj;
            }
        }
        if (soapObject.hasProperty("cod_type"))
        {
            Object obj = soapObject.getProperty("cod_type");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                cod_type = j.toString();
            }else if (obj!= null && obj instanceof String){
                cod_type = (String) obj;
            }
        }
        if (soapObject.hasProperty("selected_num_emi"))
        {
            Object obj = soapObject.getProperty("selected_num_emi");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                selected_num_emi = j.toString();
            }else if (obj!= null && obj instanceof String){
                selected_num_emi = (String) obj;
            }
        }
        if (soapObject.hasProperty("per_emi"))
        {
            Object obj = soapObject.getProperty("per_emi");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                per_emi = j.toString();
            }else if (obj!= null && obj instanceof String){
                per_emi = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return store_id;
            case 1:
                return store_name;
            case 2:
                return invoice_prefix;
            case 3:
                return store_url;
            case 4:
                return customer_id;
            case 5:
                return customer_group_id;
            case 6:
                return firstname;
            case 7:
                return lastname;
            case 8:
                return email;
            case 9:
                return telephone;
            case 10:
                return fax;
            case 11:
                return custom_field;
            case 12:
                return payment_firstname;
            case 13:
                return payment_lastname;
            case 14:
                return payment_company;
            case 15:
                return payment_address_1;
            case 16:
                return payment_address_2;
            case 17:
                return payment_city;
            case 18:
                return payment_postcode;
            case 19:
                return payment_country;
            case 20:
                return payment_country_id;
            case 21:
                return payment_zone;
            case 22:
                return payment_zone_id;
            case 23:
                return payment_district_id;
            case 24:
                return payment_subzone_id;
            case 25:
                return payment_address_format;
            case 26:
                return payment_custom_field;
            case 27:
                return payment_method;
            case 28:
                return payment_code;
            case 29:
                return shipping_firstname;
            case 30:
                return shipping_lastname;
            case 31:
                return shipping_company;
            case 32:
                return shipping_address_1;
            case 33:
                return shipping_address_2;
            case 34:
                return shipping_city;
            case 35:
                return shipping_postcode;
            case 36:
                return shipping_country;
            case 37:
                return shipping_country_id;
            case 38:
                return shipping_zone;
            case 39:
                return shipping_zone_id;
            case 40:
                return shipping_district_id;
            case 41:
                return shipping_subzone_id;
            case 42:
                return shipping_address_format;
            case 43:
                return shipping_custom_field;
            case 44:
                return shipping_method;
            case 45:
                return shipping_code;
            case 46:
                return comment;
            case 47:
                return total;
            case 48:
                return affiliate_id;
            case 49:
                return commission;
            case 50:
                return marketing_id;
            case 51:
                return tracking;
            case 52:
                return language_id;
            case 53:
                return currency_id;
            case 54:
                return currency_code;
            case 55:
                return currency_value;
            case 56:
                return ip;
            case 57:
                return forwarded_ip;
            case 58:
                return user_agent;
            case 59:
                return accept_language;
            case 60:
                return emi;
            case 61:
                return method;
            case 62:
                return totalamt;
            case 63:
                return shipping_charge;
            case 64:
                return down_payment;
            case 65:
                return each_emi;
            case 66:
                return customer_type;
            case 67:
                return no_of_emi;
            case 68:
                return payable_mrp;
            case 69:
                return vat;
            case 70:
                return cod_type;
            case 71:
                return selected_num_emi;
            case 72:
                return per_emi;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 73;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "store_id";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "store_name";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "invoice_prefix";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "store_url";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "customer_id";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "customer_group_id";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "firstname";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "lastname";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "email";
                break;
            case 9:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "telephone";
                break;
            case 10:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "fax";
                break;
            case 11:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "custom_field";
                break;
            case 12:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_firstname";
                break;
            case 13:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_lastname";
                break;
            case 14:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_company";
                break;
            case 15:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_address_1";
                break;
            case 16:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_address_2";
                break;
            case 17:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_city";
                break;
            case 18:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_postcode";
                break;
            case 19:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_country";
                break;
            case 20:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_country_id";
                break;
            case 21:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_zone";
                break;
            case 22:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_zone_id";
                break;
            case 23:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_district_id";
                break;
            case 24:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_subzone_id";
                break;
            case 25:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_address_format";
                break;
            case 26:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_custom_field";
                break;
            case 27:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_method";
                break;
            case 28:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payment_code";
                break;
            case 29:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_firstname";
                break;
            case 30:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_lastname";
                break;
            case 31:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_company";
                break;
            case 32:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_address_1";
                break;
            case 33:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_address_2";
                break;
            case 34:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_city";
                break;
            case 35:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_postcode";
                break;
            case 36:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_country";
                break;
            case 37:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_country_id";
                break;
            case 38:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_zone";
                break;
            case 39:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_zone_id";
                break;
            case 40:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_district_id";
                break;
            case 41:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_subzone_id";
                break;
            case 42:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_address_format";
                break;
            case 43:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_custom_field";
                break;
            case 44:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_method";
                break;
            case 45:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_code";
                break;
            case 46:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "comment";
                break;
            case 47:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "total";
                break;
            case 48:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "affiliate_id";
                break;
            case 49:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "commission";
                break;
            case 50:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "marketing_id";
                break;
            case 51:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "tracking";
                break;
            case 52:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "language_id";
                break;
            case 53:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "currency_id";
                break;
            case 54:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "currency_code";
                break;
            case 55:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "currency_value";
                break;
            case 56:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ip";
                break;
            case 57:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "forwarded_ip";
                break;
            case 58:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "user_agent";
                break;
            case 59:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "accept_language";
                break;
            case 60:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "emi";
                break;
            case 61:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "method";
                break;
            case 62:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "totalamt";
                break;
            case 63:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "shipping_charge";
                break;
            case 64:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "down_payment";
                break;
            case 65:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "each_emi";
                break;
            case 66:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "customer_type";
                break;
            case 67:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "no_of_emi";
                break;
            case 68:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "payable_mrp";
                break;
            case 69:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "vat";
                break;
            case 70:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "cod_type";
                break;
            case 71:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "selected_num_emi";
                break;
            case 72:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "per_emi";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
