package com.emiadda.wsdl.customerOrder;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 04/07/2016
//
//---------------------------------------------------



public interface DUHIServiceEvents
{
    public void Starting();
    public void Completed(DUHOperationResult result);
}
