package com.emiadda.wsdl.productdetails;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 06/07/2016
//
//---------------------------------------------------



public interface FELIServiceEvents
{
    public void Starting();
    public void Completed(FELOperationResult result);
}
