package com.emiadda.wsdl.specialProducts;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.0
//
// Created by Quasar Development at 15/07/2016
//
//---------------------------------------------------



public interface KESIServiceEvents
{
    public void Starting();
    public void Completed(KESOperationResult result);
}
