package com.emiadda.wsdl.specialProducts;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.8.0
//
// Created by Quasar Development at 15/07/2016
//
//---------------------------------------------------



public class KESOperationResult< T>
{
    public java.lang.Exception Exception;
    public T Result;
    public java.lang.Object Tag;
    public java.lang.String MethodName;
}
