package com.emiadda.wsdl.customerLogin;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.7.1
//
// Created by Quasar Development at 04/07/2016
//
//---------------------------------------------------



public interface WBNIServiceEvents
{
    public void Starting();
    public void Completed(WBNOperationResult result);
}
